name: Unit Testing
run-name: Unit Testing triggered by ${{ github.actor }}
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
    paths:
      - '**.pp'
      - '**.lpr'
      - '**.cfg'
  pull-request:
    types: [opened, reopened]
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Install FPC
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y fpc
      - uses: actions/checkout@v4
      - name: Create directories
        run: |
          mkdir ./bin
          mkdir ./src/obj/
          mkdir ./tests/bin/
          mkdir ./tests/obj/
      - name: Compile project
        run: |
          cd src
          fpc @debug.cfg MathXEval.lpr
      - name: Compile test project
        run: |
          cd tests
          fpc @debug.cfg TestProject.lpr
      - name: Run tests
        run: tests/bin/TestProject --all --format=plain
