name: Unit Testing
run-name: Unit Testing triggered by ${{ github.actor }}
on: [push]
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Install FPC
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y fpc
      - uses: actions/checkout@v4
      - name: Compile project
        run: |
          cd ${{ github.workspace }}/src/
          fpc @debug.cfg ${{ github.workspace }}/src/MathXEval.lpr
      - name: Compile test project
        run: |
          cd ${{ github.workspace }}/tests/
          fpc @debug.cfg ${{ github.workspace }}/tests/TestProject.lpr
      - name: Run tests
        run: |
          cd ${{ github.workspace }}/tests/
          ./bin/MathXEval
