name: Unit Testing
run-name: Unit Testing triggered by ${{ github.actor }}
on: [push]
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Install FPC
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y fpc
      - uses: actions/checkout@v4
      - name: Create directories
        run: |
          pwd
          mkdir ${{ github.workspace }}/bin
          echo "${{ github.workspace }}/src/$(fpc -iTP)-$(fpc -iTO)" | xargs mkdir
          mkdir tests/bin/
          echo "${{ github.workspace }}/tests/$(fpc -iTP)-$(fpc -iTO)" | xargs mkdir
      - name: Compile project
        run: |
          cd ${{ github.workspace }}/src
          fpc @debug.cfg MathXEval.lpr
      - name: Compile test project
        run: |
          cd ${{ github.workspace }}/tests
          fpc @debug.cfg TestProject.lpr
      - name: Run tests
        run: bin/TestProject
